steps:
  - checkout: self
    clean: true
    submodules: false
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      persistCredentials: true
    fetchTags: true
    fetchDepth: 3
